name: Airbnb CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  lint:
    name: Run Python Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install flake8
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run flake8
        run: |
          flake8 . --count --select=E9,F7,F82 --show-source --statistics
